
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtGui import QMovie
from PyQt5.QtWidgets import QApplication, QMainWindow, QTextBrowser, QPushButton,QTextEdit
from PyQt5.QtCore import QThread
from PyQt5.QtCore import QTextStream
import os
import subprocess
import webbrowser
from PyQt5.QtCore import QTimer, QTime, QDate, QBuffer

from Maya import MainExecution

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, 0, 1001, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(740, 20, 181, 241))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\iron_man.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.movie1=QMovie("GUI\\iron_man.gif")
        self.label_2.setMovie(self.movie1)
        self.movie1.start()
        
        
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, -30, 271, 141))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\initial.gif"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.movie2=QMovie("GUI\\initial.gif")
        self.label_3.setMovie(self.movie2)
        self.movie2.start()
        
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 280, 550, 200))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\UI\\loader.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.movie3=QMovie("GUI\\loader.gif")
        self.label_4.setMovie(self.movie3)
        self.movie3.start()
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 110, 401, 241))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\Siri.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.movie4=QMovie("GUI\\Siri.gif")
        self.label_5.setMovie(self.movie4)
        self.movie4.start()
        
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 450, 101, 41))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\Start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(200, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.start_clicked)
        
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 450, 101, 41))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\Quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(200, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.exit_clicked)
        
        
        
#         self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
#         self.textEdit_3.setGeometry(QtCore.QRect(750, 290, 201, 241))
#         self.textEdit_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
# "color: rgb(255, 255, 255);\n"
# "")
#         self.textEdit_3.setObjectName("textEdit_3")
        #sys.stdout = EmittingStream(self.textEdit_3)
        #sys.stdin = EmittingStream(self.textEdit_3)

       
       
        
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 190, 121, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\youtube-logo.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(180, 65))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.startyoutube)
                
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 240, 111, 31))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\chrome-logo-800x400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(180, 65))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.startChrome)
        
        
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 290, 121, 31))
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton_6.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\whatsaap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(500, 60))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.startwhatsapp)
        
        
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 340, 121, 31))
        self.pushButton_7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\Archana\\Desktop\\MAYA\\GUI\\google-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(450, 100))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.startgoogle)
        
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(540, 20, 151, 41))
        self.textBrowser_2.setFont(QFont('Arial', 8))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.timer = QTime()
        
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(310, 20, 151, 41))
        self.textBrowser_4.setFont(QFont('Arial', 8))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.timer = QTimer()
 
        # adding action to timer
        self.timer.timeout.connect(self.showTime)
        self.timer.timeout.connect(self.showDate)
 
        # update the timer every second
        self.timer.start(1000)
        
        
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_7.raise_()
        self.pushButton_6.raise_()
        #self.textEdit_3.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    
    def startChrome(self):
     os.startfile(r"C:\Program Files\Google\Chrome\Application\chrome.exe")
    
    
    def startyoutube(self):
     webbrowser.open("https://www.youtube.com/")
    
    def startgoogle(self):
      webbrowser.open("https://www.google.com/")\
      
    def startwhatsapp(self):
      webbrowser.open("https://web.whatsapp.com/")  
    
    def showTime(self):
 
      # getting current time
      current_time = QTime.currentTime()
   
      # converting QTime object to string
      label_time = current_time.toString('hh:mm:ss')
   
      # showing it to the label
      self.textBrowser_4.setText(label_time)
    
    def showDate(self):
 
      # getting current time
      current_date = QDate.currentDate()
   
      # converting QTime object to string
      label_time = current_date.toString('dd:MM:yyyy')
   
      # showing it to the label
      self.textBrowser_2.setText(label_time)  
      
    def start_clicked(self):
      self.worker=workerThread()
      self.worker.start()
       
       
        
    def exit_clicked(self):
        exit()
    
        
class EmittingStream(QTextEdit):
    def write(self, text):
        self.append(text)   
        
class workerThread(QThread):
    def run(self):
       MainExecution()    

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

